from typing import Protocol, Any

class IncidentDetector(Protocol):
    def detect(self, records: list[dict[str, Any]]) -> list[dict[str, Any]]: ...
class RecoveryProbabilityModel(Protocol):
    def predict(self, features: list[dict[str, Any]]) -> list[float]: ...
class UpliftEstimator(Protocol):
    def estimate(self, features: list[dict[str, Any]]) -> list[float]: ...
class RevenueRiskEstimator(Protocol):
    def estimate(self, records: list[dict[str, Any]]) -> dict[str, Any]: ...
